language: rust
cache: cargo

rust:
  - nightly

env:
  - RUST_BACKTRACE=1 RUST_TEST_THREADS=1

services:
  - docker

before_install:
  - docker pull mariadb:10.4.5
  - docker run -d --name mariadb -e MYSQL_ROOT_PASSWORD=supersecretpassword mariadb:10.4.5
  - docker inspect mariadb
