language: rust

rust:
  - nightly-2020-06-09

env:
  - CODECOV_TOKEN="7743ab68-b2c4-485c-8954-24b8424e7922" RUST_BACKTRACE=1 RUST_TEST_THREADS=1

services:
  - docker


before_install:
  - docker pull mariadb:10.5.3
  - docker run -d --name mariadb -e MYSQL_ROOT_PASSWORD=supersecretpassword mariadb:10.5.3
  - docker inspect mariadb
  - cargo install cargo-tarpaulin

script:
  - cargo tarpaulin --out Xml
  - bash <(curl -s https://codecov.io/bash)

