[package]
name = "bookwerx-core-rust"
version = "0.2.0" #  Keep this in sync with the CLI config in main.rs and dbseed.rs
authors = ["Thomas Radloff <bostontrader@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33" # Command line args
mysql = "16.0.0"
rocket = "0.4.2"
# rocket_contrib = "0.4.2"
rust_decimal = "1.0.1"

# These are actually dev-dependencies.  But if I configure them so, then I cannot generate documentation for them.  Hence, do this.
assert_cmd = "0.11.1"
predicates = "1.0.1"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["mysql_pool"]