[package]
name = "bookwerx-core-rust"
version = "0.7.0" #  Keep this in sync with the CLI config in main.rs and dbseed.rs as well as the "/" route.
authors = ["Thomas Radloff <bostontrader@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33" # Command line args
mysql = "16.0.2"
rand = "0.7.0"
rocket = "0.4.2"

# The existing versions of rocket_cors and rocket_contrib have incompatible dependency requirements regarding their mutual dependency 'regex'. I have resolved this by forking rocket_cors and tweaking the regex version.
#rocket_cors = "0.5.0"
rocket_cors = { git = "https://github.com/bostontrader/rocket_cors", branch = "downgrade-regex" }
rust_decimal = "1.0.1"
serde = "1.0.95"
serde_json = "1.0.40"

[dev-dependencies]
assert_cmd = "0.11.1"
predicates = "1.0.1"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json","mysql_pool"]