[package]
name = "bookwerx-core-rust"
version = "0.1.1" #
authors = ["Thomas Radloff <bostontrader@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33" # Command line args

# These are actually dev-dependencies.  But if I configure them so, then I cannot generate documentation for them.  Hence, do this.
assert_cmd = "0.11.1"
predicates = "1.0.1"